### ISSUE TITLE
Notes not getting downloaded

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#334]
Clicking on the download button opens a new tab but nothing downloads
Tried in chrome

**Comment by devsargam** [comment]
@hkirat the problem is it works on local setup. Cant really figure out what is going wrong 😞

**Comment by hkirat** [comment]
hmm got it

**Comment by nimit9** [comment]
Will try to check what might be going wrong in prod.

**Comment by dyaipayan22** [comment]
@hkirat upon reading about the issue, I figured out that **relative path fails to download file in production**. You need to provide the **absolute url of the notion doc**. On changing the <Link href={`/pdf/${id}`} target="_blank"> to <Link href={`${notion_doc_url}` target="_blank"}> in the NotionRenderer.tsx should solve the issue in production.

**Comment by neeshant-pandey** [comment]
The application currently utilizes an external link to facilitate the downloading of content as a PDF. This method requires users to navigate away from the app, potentially leading to a disjointed user experience.

I propose implementing an in-app PDF generation and download feature using react-to-print. This solution involves:
Using useRef to directly reference the content that needs to be printed.
Employing useReactToPrint for on-the-fly PDF generation and download, triggered by a button within the app.
I have implemented the solution locally 

![image](https://github.com/code100x/cms/assets/50216304/8b36f8be-f5ef-459c-bdc1-fa0e357573a8)

Keeps users within the app, streamlining the process of converting content into a PDF.

**Comment by Neon-20** [comment]
Hey I have implemented the following as well, if you are not raising a PR I will raise it. @hkirat @neesh

Thanks

https://github.com/code100x/cms/assets/55043383/2d084854-50f3-45c4-a45c-a62f6fe375d1

**Comment by neeshant-pandey** [comment]
Hi @Neon-20 I am raising a PR.
Thanks!

**Comment by Neon-20** [comment]
Sure Go Ahead @neeshant-pandey

**Comment by mumin-khan** [comment]
The reason the issue was not found in local is most likely because the note is small and hence the function works before closing.
https://app.100xdevs.com/courses/3/234/258
Try this in chrome, it also get downloaded in production.

**Comment by vimulatus** [comment]
Hi, the issue is still there for certain notes. Trying this [here](https://app.100xdevs.com/courses/3/234/258), the print dialog does open but [here](https://app.100xdevs.com/courses/3/248/266), it doesn't.

**Comment by hkirat** [comment]
seems like this is fixed now?
